### ISSUE TITLE
Not taking mate in 1

### ISSUE THREAD

**Issue by hwuebben** [andrefpf/deep-duck#1]
Hey, nice project!
I was playing around a bit and was wondering why the engine wouldn't take the mate in 1 in this position:
8/1Q2k3/6Q1/4QQ2/8/8/1K6/*7 w - - 0 1

Obviously it is won either way but I think it would be good for a tool like this to always show the shortest path to victory.

Cheers.

**Comment by andrefpf** [comment]
Hi,

The engine really doesn't care for short mates. That would be a nice and easy addition.

Thank you,

**Comment by andrefpf** [comment]
Bug fixed
